name: "rec-sys"
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scipy
  - tqdm
  - loguru
  - scikit-learn
  - wandb=0.19.10
  - python-dotenv
  - pyspark=3.5.5